version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      remix:
        patterns:
          - "@remix-run/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
          - "react-router-dom"
      fonts:
        patterns:
          - "@fontsource/*"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "@vitest/*"
          - "jsdom"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
      build-tools:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "typescript"
    open-pull-requests-limit: 10